version: '2'
services:
  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
  console:
    image: saturn/saturn-console:master-SNAPSHOT
    container_name: saturn_console 
    restart: always
    links:
      - zookeeper
    ports:
      - 9088:9088
  demo-init:
    image: saturn/demo-init
    container_name: demo-init
    volumes: 
      - /saturn-executor-master-SNAPSHOT/apps
    links:
      - zookeeper
    depends_on:
      - console            
  executor-a:
    image: saturn/saturn-executor:master-SNAPSHOT
    container_name: saturn_executor_a
    restart: always
    links:
      - zookeeper
    volumes_from:
      - demo-init
  executor-b:
    image: saturn/saturn-executor:master-SNAPSHOT
    container_name: saturn_executor_b
    restart: always
    links:
      - zookeeper
    volumes_from:
      - demo-init